Make one-time.html more generic.
chromium/permission.site pull request #116
Opened 2024-05-30 19:55 UTC by panmari

The page is also useful for testing other features, e.g. behavior of the permission API across browsers.

2024-05-30 21:23 UTC, lgarron requested changes
If `one-time.html` is going to move, I think it should have a redirect. Since we're using GitHub Pages, that will need a `<meta>` redirect.

If we're moving it, I would also slightly prefer `/permision-status/` (i.e. using a file at `/permision-status/index.html`) rather than `/permission-status.html`, but that's more a matter of opinion.

2024-05-31 07:11 UTC, panmari commented
> If `one-time.html` is going to move, I think it should have a redirect. Since we're using GitHub Pages, that will need a `<meta>` redirect.
> 
> If we're moving it, I would also slightly prefer `/permision-status/` (i.e. using a file at `/permision-status/index.html`) rather than `/permission-status.html`, but that's more a matter of opinion.

Makes sense, done.

2024-05-31 11:11 UTC, engedy requested changes
LGTM % smaller comments. Thanks!

2024-05-31 11:11 UTC, engedy commented on one-time.html
> -          <li>
I think this might be interesting to preserve, but maybe phrase it like:

            Navigate to a <a href="">page</a> from the current origin in the current tab, or another tab, and compare the permissions state to what you set here. In some user agents, a certain amount of time elapsing, closing all tabs from an origin, and/or having all tabs from an origin in the background for a certain duration will reset the permission state.

2024-05-31 11:11 UTC, engedy commented on permission-status/index.html
> +  <title>permission.site (one-time)</title>
Let's update the title here as well to `permisision.site (PermissionStatus)`

2024-05-31 11:11 UTC, engedy commented on permission-status/index.html
> +          Close the tab. Reopen it. Observe that if you only granted permission for a single request, the <span class="permission-status">permission
nit: Observe that based on the permission permanence model implemented by the user agent, the permission may or may not revert back to the "prompt" state.

2024-05-31 11:45 UTC, panmari commented on one-time.html
> -          <li>
Added some version of this. Did you mean "window" in some places?

2024-05-31 12:03 UTC, engedy commented on one-time.html
> -          <li>
Technically, "window" is the language used in spec, but practically folks will be testing with tabs. The current wording should be good.

2024-05-31 12:04 UTC, engedy approved these changes
LGTM, thanks!

2024-06-03 06:59 UTC, panmari commented
@lgarron did I address your concerns?

2024-06-06 10:52 UTC, engedy commented
I'm going to go ahead and merge this in the interest of expediency, Lucas, let us know if you have any additional concerns.

2024-06-06 10:53 UTC, merged

2024-06-07 05:44 UTC, lgarron reviewed
I had a few leftover nits, but no worries!

2024-06-07 05:44 UTC, lgarron commented on permission-status/index.html
> +</html>
Files should still end in newlines.

2024-06-07 05:44 UTC, lgarron commented on permission-status/other-page.html
> +    <a href="index.html">Back to the permission status demo page</a>
I would have stuck with `./` to match the folder path.

2024-06-07 08:27 UTC, engedy commented
@panmari Could you please send us a PR to address those nits?

2024-06-08 20:18 UTC, panmari commented
I addressed the nits in #118

2024-06-10 09:13 UTC, engedy commented
Thank you, approved that.