Add Device Orientation/Motion permission requests
chromium/permission.site pull request #88
Opened 2021-11-08 08:16 UTC by FluorescentHallucinogen

Spec:

* `DeviceOrientationEvent.requestPermission()`: https://w3c.github.io/deviceorientation/#dom-deviceorientationevent-requestpermission
* `DeviceMotionEvent.requestPermission()`: https://w3c.github.io/deviceorientation/#dom-devicemotionevent-requestpermission

Implementations:

* WebKit (iOS): https://bugs.webkit.org/show_bug.cgi?id=195329
* Chromium (WIP): https://crbug.com/947112

2021-11-09 10:52 UTC, FluorescentHallucinogen commented
@engedy @lgarron PTAL. :wink:

2021-11-09 16:15 UTC, lgarron commented on index.html
> +    Currently, only WebKit on iOS <a href="https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes">requires</a>
Is this a statement about all browsers, or just Chrome-based/branded ones?

2021-11-09 16:28 UTC, FluorescentHallucinogen commented on index.html
> +    Currently, only WebKit on iOS <a href="https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes">requires</a>
I'm not sure I understand the question. In iOS all browsers (including Chrome, Firefox, etc.) are forced to use WebKit instead of their own engines.

2021-11-09 16:35 UTC, lgarron commented on index.html
> +    Currently, only WebKit on iOS <a href="https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes">requires</a>
That partially answers the question! Do you mean to also declare that no other browser on any other OS will show a prompt?

2021-11-09 16:47 UTC, FluorescentHallucinogen commented on index.html
> +    Currently, only WebKit on iOS <a href="https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes">requires</a>
I don't think this is a good idea, because this may change in the near future. See e.g. https://crbug.com/947112.

What about more generic `May succeed without permission depending on the implementation.` phrase without any specific mention like in https://github.com/chromium/permission.site/blob/master/index.html#L85?

2021-11-09 16:49 UTC, lgarron commented on index.html
> +    Currently, only WebKit on iOS <a href="https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes">requires</a>
> What about more generic `May succeed without permission depending on the implementation.` phrase without any specific mention like in https://github.com/chromium/permission.site/blob/master/index.html#L85?

Yeah, I think that would work better.
If you want to keep it informative without getting out of date, you could also add something like "As of 2021-11-09, ..." about WebKit.

2021-11-09 17:56 UTC, FluorescentHallucinogen commented
@lgarron All is done. Could you please merge this pull request?

2021-11-10 00:25 UTC, engedy commented on index.js
> +          displayOutcome("orientation", "success")("window.DeviceOrientationEvent doesn't require permission request");
What do you think about waiting for the first DeviceOrientationEvent here, and setting "success" or "error" based on whether the coordinates (i.e. `alpha`/`beta`/`gamma` attributes of the event) are non-null or null, respectively?

That mechanism for detection would be more consistent with the spec [1], which says: "if an implementation can never provide orientation information, the event should be fired with the alpha, beta and gamma attributes set to null".

Plus, that would also be consistent with the behavior that `permission.site` currently has for things like camera/microphone, where the button turns red if you don't have the respective media input device.

[1]: https://www.w3.org/TR/orientation-event/#deviceorientation , see last sentence in this section.

2021-11-10 00:26 UTC, engedy requested changes

2021-11-10 00:26 UTC, engedy commented on index.js
> +          displayOutcome("motion", "success")("window.DeviceMotionEvent doesn't require permission request");
Same suggestion here.

2021-11-10 00:37 UTC, engedy commented
Lucas, you are now marked as a co-author on this PR with your c@g.n email address. Would it be possible for you to sign the CLA with this email address?

2021-11-10 00:52 UTC, lgarron commented
> @lgarron , you are now marked as a co-author on this PR with your [c@g.n](mailto:c@g.n) email address. Would it be possible for you to sign the CLA with this email address?

Sure, I'm actually surprised this hasn't come up before. :-P

But the CLA process seems to suggest that I have to add it as an [alternative email](https://support.google.com/accounts/answer/176347) to my main GMail account, which I definitely don't want to. Do you know if there's another process I can use?

2021-11-10 01:33 UTC, engedy commented
> > @lgarron , you are now marked as a co-author on this PR with your [c@g.n](mailto:c@g.n) email address. Would it be possible for you to sign the CLA with this email address?
> 
> Sure, I'm actually surprised this hasn't come up before. :-P
> 
> But the CLA process seems to suggest that I have to add it as an [alternative email](https://support.google.com/accounts/answer/176347) to my main GMail account, which I definitely don't want to. Do you know if there's another process I can use?

Looks like an edge case where the solution was for me to manually override. I confirmed that you signed the CLA with this Github username with an other email address.

2021-11-15 14:45 UTC, FluorescentHallucinogen commented on index.js
> +          displayOutcome("orientation", "success")("window.DeviceOrientationEvent doesn't require permission request");
Done.

2021-11-15 14:46 UTC, FluorescentHallucinogen commented on index.js
> +          displayOutcome("motion", "success")("window.DeviceMotionEvent doesn't require permission request");
Done.

2021-11-16 18:06 UTC, FluorescentHallucinogen commented
@engedy @lgarron All code review feedback has been addressed. Could you please take a look again and merge this pull request?

2021-11-18 11:44 UTC, engedy commented on index.js
> +        if (window.DeviceOrientationEvent && window.DeviceOrientationEvent.requestPermission) {
The spec is not entirely clear on how the permission request process influences how and when the events are fired (if at all), and how all of this is affected if the sensors are not available on the device.

What do you think about restructuring the control flow here a little bit to be more accommodative of various implementations that could make sense here? What I had in mind is something like this:

0. If `ondeviceorientation` is not supported, display "error" outcome. Fin.
1. If `DeviceOrientationEvent.requestPermission` is not supported, go to step 3.
2. Call `DeviceOrientationEvent.requestPermission()`.
2.1. If promise resolves with "granted", go to step 3.
2.2. If promise resolves with not "granted", or rejects, display "error" outcome, with appropriate details. Fin.
3. Add the `deviceorientation` event handler the same way we currently do above.

2021-11-18 11:44 UTC, engedy commented on index.js
> +              if (permissionState === "denied") {
We probably want to check for !== "granted" here. The `permissionState` could also be "prompt", meaning the user did not make a decision. The site does not get access to the capability but can ask again.

2021-11-18 11:44 UTC, engedy commented on index.js
> +      if ("ondevicemotion" in window) {
I would suggest the same restructuring here.

2021-11-18 18:33 UTC, FluorescentHallucinogen commented on index.js
> +              if (permissionState === "denied") {
Fixed. But I found that spec is controversial — https://w3c.github.io/deviceorientation/#id=permission-model has 3 values: `default`, `denied`, `granted`, but https://w3c.github.io/deviceorientation/#enumdef-permissionstate has only 2 values: `granted`, `denied`.

2021-11-18 19:42 UTC, FluorescentHallucinogen commented on index.js
> +        if (window.DeviceOrientationEvent && window.DeviceOrientationEvent.requestPermission) {
Please take a look at my code again. ;)

> If ondeviceorientation is not supported, display "error" outcome. Fin.

This is exactly how it's currently done.

> If promise resolves with "granted", go to step 3.

To catch the event, we need to add the listener *before* the event occurs.

It's enough to add one listener once as early as possible and it will wait for the event.

If `requestPermission()` is not implemented, the event dispatches immediately.

If `requestPermission()` is implemented, we should call it, and the event dispatches once `requestPermission` promise resolves.

I've tested this on iOS (the only `requestPermission()` implementation at the moment) and it works. :)

2021-11-18 19:43 UTC, FluorescentHallucinogen commented on index.js
> +      if ("ondevicemotion" in window) {
See https://github.com/chromium/permission.site/pull/88#discussion_r752571535.

2021-11-19 11:29 UTC, engedy commented on index.js
> +              if (permissionState === "denied") {
Yes, that is inconsistent. Can you please file a bug against the spec (https://github.com/w3c/deviceorientation/issues)?

2021-11-19 11:40 UTC, engedy commented on index.js
> +        if (window.DeviceOrientationEvent && window.DeviceOrientationEvent.requestPermission) {
The iOS/WebKit behavior you describe matches my understanding based on [1], however, as you can see on the issue, there is still not consensus on what exactly the behavior should be if you register the event handler and call `requestPermission()` later.

My thinking was that calling `requestPermission()` first, and registering the event handler later, would be the most robust solution that accommodates most reasonable implementations within the space allowed by the spec. This all is of course predicated on the assumption that this approach works on WebKit as well, but I would be rather surprised if it didn't. 

WDYT?

[1]: https://github.com/w3c/deviceorientation/issues/74#issuecomment-480981479

2021-11-20 09:29 UTC, FluorescentHallucinogen commented on index.js
> +        if (window.DeviceOrientationEvent && window.DeviceOrientationEvent.requestPermission) {
Since `requestPermission()` was added to the spec / implemented in the browsers *after* `deviceorientation` and `devicemotion` events, I would prefer to call `requestPermission()` *after* adding the listeners for `deviceorientation` and `devicemotion` events, because

1. `requestPermission()` must be non-breaking
2. event listeners, in fact, can be added at any time, and independent from `requestPermission()`

Otherwise, we'll lose useful `[Warning] No device orientation events will be fired, reason: Permission to use the API was not yet requested` and `[Warning] No device motion events will be fired, reason: Permission to use the API was not yet requested` warnings.

Displaying these logs is a part of test of how browsers handle this case.

2021-11-22 12:34 UTC, engedy commented on index.js
> +        if (window.DeviceOrientationEvent && window.DeviceOrientationEvent.requestPermission) {
That makes sense, thanks for explaining your approach.

2021-11-22 12:34 UTC, engedy commented on index.js
> +      if ("ondeviceorientation" in window) {
style nit: To avoid arrow code, let's restructure this to:

```
  if (!("ondeviceorientation" in window))
    return;
```

2021-11-22 18:24 UTC, FluorescentHallucinogen commented on index.js
> +        }, { once: true });
Are you suggesting to remove `{ once: true }`?

2021-11-23 16:29 UTC, engedy commented on index.js
> +        }, { once: true });
I cannot immediately think of any issues, so as long as you can't either, let's go with that simple solution.

2021-11-29 18:02 UTC, FluorescentHallucinogen commented on index.js
> +              console.log(`Permission state: ${permissionState}`);
Done.

2021-11-29 18:15 UTC, FluorescentHallucinogen commented on index.js
> +        }, { once: true });
I've used `{ once: true }` to avoid high frequent `displayOutcome("orientation", "success")("Device has the required sensors");` console logs and unnecessary high frequent button re-renders.

I eventually came up with the solution you suggested in https://github.com/chromium/permission.site/pull/88#discussion_r752161144. This solves the hypothetical problem you described in https://github.com/chromium/permission.site/pull/88#discussion_r754229909. But we loose `[Warning] No device orientation events will be fired, reason: Permission to use the API was not yet requested` and `[Warning] No device motion events will be fired, reason: Permission to use the API was not yet requested` warnings mentioned by me in https://github.com/chromium/permission.site/pull/88#discussion_r753655626.

2021-11-29 18:31 UTC, FluorescentHallucinogen commented on index.js
> +        if (window.DeviceOrientationEvent && window.DeviceOrientationEvent.requestPermission) {
TBH, I don't see any benefits of `if (!window.DeviceOrientationEvent || !window.DeviceOrientationEvent.requestPermission)` over `if (window.DeviceOrientationEvent && window.DeviceOrientationEvent.requestPermission)`. Here's my arguments:

1. Two unnecessary negatives in || variant vs. zero in && variant
2. IDE can find and suggest refactoring of && variant to optional chain:

![optional-chain-refactoring](https://user-images.githubusercontent.com/7892779/143922175-4d2002b1-a77f-4b0f-ba48-81536a7d4aa9.gif)

3. This is consistent with the style of code above and below

2021-11-29 18:31 UTC, FluorescentHallucinogen commented on index.js
> +      if ("ondeviceorientation" in window) {
See https://github.com/chromium/permission.site/pull/88#discussion_r758631511.

2021-11-29 19:39 UTC, engedy commented on index.js
> +        if (window.DeviceOrientationEvent && window.DeviceOrientationEvent.requestPermission) {
Yeah, the negation would be much easier if we had widespread support for optional chain, without it it is a bit ugly. I am happy with this either way. :-)

2021-11-29 19:40 UTC, engedy commented on index.js
> +      if ("ondeviceorientation" in window) {
Ack.

2021-11-29 19:45 UTC, FluorescentHallucinogen commented on index.js
> +        }, { once: true });
I'm ok to loose these logs. ;)

2021-11-29 19:53 UTC, engedy commented on index.js
> +        const handleDeviceMotion = window.addEventListener("devicemotion", (event) => {
Let's not forget the `() =>` here.

2021-11-29 19:53 UTC, engedy commented on index.js
> +        }, { once: true });
I am happy with this solution, thanks!

2021-11-29 19:56 UTC, FluorescentHallucinogen commented on index.js
> +        const handleDeviceMotion = window.addEventListener("devicemotion", (event) => {
Oh, good catch! 😱 Thanks, fixed.

2021-11-29 20:23 UTC, engedy approved these changes

2021-11-29 20:29 UTC, merged