Added button for beforeunload
chromium/permission.site pull request #99
Opened 2022-08-22 09:52 UTC by RamGoel

@lgarron I have added button for "before unload" event as you've said. Thanks for Helping Out 🚀

2022-08-22 10:10 UTC, lgarron reviewed
Thanks for the revisions!
Some further thoughts, although @engedy should be the definitive say on merging.

2022-08-22 10:10 UTC, lgarron commented on index.js
> +        addEventListener('beforeunload',function(event){
Nit: Although `globalThis == window` by default, I'd suggest specifying it.
```suggestion
        window.addEventListener('beforeunload',function(event){
```

2022-08-22 10:10 UTC, lgarron commented on index.js
> +      if(confirm("Confirm before Closing Window?")){
I don't think this confirmation helps test anything — if anything, it might mess with browser heuristics. I'd suggest taking it out.

2022-08-22 10:10 UTC, lgarron commented on index.html
> +<button id="window-close">Window Close Prompt</button>
"Window Close" is not quite accurate. In lieu of another name for it, I'd suggest using the actual event name.
```suggestion
<button id="beforeunload"><code>beforeunload</code> Handler</button>
```

2022-08-22 10:10 UTC, lgarron commented on index.js
> +          return event.returnValue="";
Since most browsers used to show this string to users, this is probably the most useful place to test UA behaviour. I'd suggest setting a non-empty string, like this:
```suggestion
          return event.returnValue = "[beforeunload test] Do you want to leave this page?";
```

2022-08-22 10:43 UTC, RamGoel commented on index.js
> +      if(confirm("Confirm before Closing Window?")){
When button gets clicked, should it just simply enable without any response or give some response like `alert("The onbeforeunload handler has been enabled")`

2022-10-01 02:56 UTC, RamGoel commented
Hi @lgarron , I will be more than happy if you can help me merge this PR.

Thank You.

2022-10-04 11:55 UTC, beaufortfrancois commented
@engedy Please review.

2022-10-08 19:24 UTC, RamGoel commented
@engedy Can you review please.

2022-11-16 04:56 UTC, RamGoel commented
@beaufortfrancois Sorry to bother, but can anyone please review.

2022-11-16 05:14 UTC, lgarron commented on index.js
> +      if(confirm("Confirm before Closing Window?")){
I don't really follow the reasoning. What does this have to do with testing `beforeunload`?

2023-08-04 06:35 UTC, lgarron requested changes
Sorry, I had some pending comments from long ago. I think this is still no in a good state to land.

2023-12-15 18:34 UTC, closed without merging